services:
  fsop:
    image: fsop:latest
    platform: linux/amd64
    container_name: fsop
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - PORT_OUT_ID=${PORT_OUT_ID}
      - PORT_OUT_PW=${PORT_OUT_PW}
      - PORT_OUT_URL=${PORT_OUT_URL}
      - PORT_OUT_ID_2=${PORT_OUT_ID_2}
      - PORT_OUT_PW_2=${PORT_OUT_PW_2}
      - PORT_OUT_URL_2=${PORT_OUT_URL_2}
